version: "3.8"

services:
  landing-page:
    build:
      context: ../frontend/landing-page
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ../frontend/landing-page:/app # Mount source code for hot reload
      - /app/node_modules # Prevent overwriting node_modules
    environment:
      - NODE_ENV=development
    command: ["npm", "run", "dev"]
    networks:
      - mynetwork

  dashboard:
    build:
      context: ../frontend/user-dashboard
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ../frontend/user-dashboard:/app # Mount source code for hot reload
      - /app/node_modules # Prevent overwriting node_modules
    environment:
      - NODE_ENV=development
    command: ["npm", "run", "dev"]
    networks:
      - mynetwork

  user-service:
    build:
      context: ../backend/user-service
      dockerfile: Dockerfile
    environment:
      - PORT=8000
    ports:
      - "8000:8000"
    networks:
      - mynetwork

  auth-service:
    build:
      context: ../backend/auth-service
      dockerfile: Dockerfile
    environment:
      - PORT=8001
    ports:
      - "8001:8001"
    networks:
      - mynetwork

  notification-service:
    build:
      context: ../backend/notification-service
      dockerfile: Dockerfile
    environment:
      - PORT=8002
    ports:
      - "8002:8002"
    networks:
      - mynetwork

  real-time-service:
    build:
      context: ../backend/real-time-service
      dockerfile: Dockerfile
    environment:
      - PORT=8003
    ports:
      - "8003:8003"
    networks:
      - mynetwork

  search-service:
    build:
      context: ../backend/search-service
      dockerfile: Dockerfile
    environment:
      - PORT=8004
    ports:
      - "8004:8004"
    networks:
      - mynetwork

  task-service:
    build:
      context: ../backend/task-service
      dockerfile: Dockerfile
    environment:
      - PORT=8005
    ports:
      - "8005:8005"
    networks:
      - mynetwork

  api-gateway:
    build:
      context: ../backend/api-gateway
      dockerfile: Dockerfile
    environment:
      - PORT=8006
    ports:
      - "8006:8006"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
